#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.


# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a custom 404 error page
echo "server {
    listen 80;

    location / {
        root /var/www/html;
        index index.html;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
        rewrite ^ /custom_404.html break;
    }
}" | sudo tee /etc/nginx/sites-available/custom_404

# Create the custom 404 HTML page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo service nginx restart

