#!/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 228560-web-01 54.167.85.104:80 check
    server 228560-web-02 54.173.210.115:80 check
EOF

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy

# Ensure HAProxy is managed via an init script
sudo systemctl enable haproxy
