#!/usr/bin/env bash
# Fix Nginx to listend on port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Start Nginx
service nginx restart
