#!/bin/env bash
# Fix Nginx to listend on port 80

sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start

cd /etc/nginx/sites-enabled/ || exit
rm default
ln -s /etc/nginx/sites-available/default default

# Start Nginx
service nginx restart
