#!/usr/bin/env bash
# A Bash script that displays the PID, along with the
#+ process name, of processes whose name contain the word bash.
pids=$(pgrep -f bash)
for pid in $pids; do
	process_name=$(cat /proc/"$pid"/comm)
	if [[ $process_name == *bash* ]]; then
		echo "$pid $process_name"
	fi
done
