#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
passwd_file="/etc/passwd"
while IFS=: read -r username _ uid _ _ home _; do
	echo "$username:$uid:$home"
done < "$passwd_file"
