#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
passwd_file="/etc/passwd"
while IFS=: read -r username passwd uid gid uinfo home shell; do
        echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passwd, more info about the user here: $uinfo"
done < "$passwd_file"
