#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12
#+ display minutes from 1 to 59
hour=0
while [ $hour -lt 13 ]
do
	min=1
	echo "Hour: $hour"
	while [ $min -lt 60 ]
	do
		echo "$min"
		min=$((min + 1))
	done
	hour=$((hour + 1))
done
