#!/usr/bin/env bash
# A Bash script that displays all active IPv4
#+ IPs on the machine it’s executed on.
active_ipv4_addresses=$(ifconfig | grep -E 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{ print $2 }')

for active_ipv4_address in $active_ipv4_addresses; do
  echo "$active_ipv4_address"
done

